version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: hermes
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hermes
    ports:
      - "5432:5432"
