replicaCount: 1 

image: 
  repository: trustprovenance/hermes
  tag: latest 
  pullPolicy: Always 

service:
  name: hermes-service
  type: ClusterIP 
  port: 8080

postgres:
  image:
    repository:  postgres 
    tag: latest
    pullPolicy: IfNotPresent 
  service: 
    name: postgres
    port: 5432
  username: hermes
  password: password
  database: hermes

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

hermesService:
  port: 8080 
  databaseUrl: postgres://hermes:password@hermes:5432/hermes